{{- if .Values.serviceAccount.storage.create }}
{{- $annotations := dict }}
{{- range $key, $value := .Values.serviceAccount.storage.annotations }}
{{- $_ := set $annotations $key $value }}
{{- end }}
{{- if .Values.serviceAccount.storage.roleArn }}
{{- $_ := set $annotations "eks.amazonaws.com/role-arn" .Values.serviceAccount.storage.roleArn }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.storage.name }}
  namespace: {{ .Release.Namespace }}
{{- if gt (len $annotations) 0 }}
  annotations:
{{- range $key, $value := $annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
