{{- range $name, $service := .Values.service }}
{{- $componentName := include "tritontube.componentName" (dict "root" $ "component" $name) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $componentName }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "tritontube.labels" $ | indent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "tritontube.name" $ }}
    app.kubernetes.io/component: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ $service.port }}
      targetPort: {{ $service.targetPort }}
{{- end }}
