{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "storage-service.fullname" .) .Values.serviceAccount.name }}
  labels:
    {{- include "storage-service.labels" . | nindent 4 }}
  {{- if or .Values.serviceAccount.annotations .Values.s3.irsaRoleArn }}
  annotations:
    {{- range $k, $v := .Values.serviceAccount.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- if .Values.s3.irsaRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.s3.irsaRoleArn | quote }}
    {{- end }}
  {{- end }}
{{- end }}
