apiVersion: v1
kind: Service
metadata:
  name: {{ include "storage-service.fullname" . }}
  labels:
    {{- include "storage-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "storage-service.selectorLabels" . | nindent 4 }}
